// Work in progress.

pipeline {
    agent {
        kubernetes {
            cloud 'kubernetes'
            defaultContainer 'jnlp'
            yamlFile 'pipeline/skaffoldContainer.yaml'
        }
    }

    options {
        disableConcurrentBuilds()
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '10', numToKeepStr: '10')
    }

    parameters {
        string(name: 'REGISTRY_REPO_URL', defaultValue: 'gcr.io/hm-hands-on', description: 'イメージレジストリ')
        string(name: 'REPO_NAME', defaultValue: '', description: 'レジストリ名')
        string(name: 'NAMESPACE', defaultValue: 'msa-demo', description: 'デプロイ先のネームスペース')
    }

    triggers {
        pollSCM 'H/5 * * * *'
    }

    stages {
        stage('Validation & Envinronment info') {
            when {
                expression {
                    return ${params.REPO_NAME} != '';
                }
            }

            steps {
                container('skaffold-container') {
                    sh """
                        uname -a
                        whoami
                        pwd
                        skaffold version
                        echo ${params.REPO_NAME}
                    """
                }
            }
        }

        stage('Clone source code') {
            steps {
                checkout scm
            }
        }

        stage('RUN skaffold: Build image and deploy') {
            steps {
                script {
                    withCredentials([
                        usernamePassword(credentialsId: 'registry_id', usernameVariable: 'REGISTRY_ID_USER', passwordVariable: 'REGISTRY_ID_PASSWORD')
                    ]) {
                        container('skaffold-container') {
                            sh """
                                docker login https://${params.REGISTRY_REPO_URL} -u '${REGISTRY_ID_USER}' -p '${REGISTRY_ID_PASSWORD}'
                                skaffold run -d ${params.REGISTRY_REPO_URL}/${params.REPO_NAME} -n ${params.NAMESPACE}
                            """
                        }
                    }
                }
            }
        }

//        stage('Deploy apps') {
//            input {
//                message "Should we continue?"
//                ok "Yes, we should."
//                submitter "alice,bob"
//                parameters {
//                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
//                }
//            }
//        }

    }
//    post {
//        always {
//            echo "Post process..."
//        }
//    }
}
