// Environment parameterize
// Set ${REGISTRY_REPO_URL}, ${REPO_NAME}, skaffold images ${SKAFFOLD_IMAGE}
// username and password: registry_id from Jenkins UI.

def scmVars // please refer this instance if you need scm information.

podTemplate(
  label: 'skaffold',
  cloud: 'kubernetes',
  containers: [
    containerTemplate(name: 'skaffold-insider', image: 'gcr.io/hm-hands-on/library/skaffold-docker:1.0-v0.34.0', ttyEnabled: true, command: 'cat', alwaysPullImage: true)
  ],
  volumes: [
    hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock')
  ]
) {
  node('skaffold') {
    withCredentials([
      usernamePassword(credentialsId: 'registry_id', usernameVariable: 'REGISTRY_ID_USER', passwordVariable: 'REGISTRY_ID_PASSWORD')
    ]) {
      stage('Info') {
        container('skaffold-insider') {
          sh """
            uname -a
            whoami
            pwd
            ls -al
          """
        }
      }
      
      stage('Clone source code') {
        scmVars = checkout scm
      }

      stage('Run skaffold') {
        container('skaffold-insider') {
          sh """
            docker login https://${REGISTRY_REPO_URL} -u ${REGISTRY_ID_USER} -p ${REGISTRY_ID_PASSWORD}
            skaffold run -d ${REGISTRY_REPO_URL}/${REPO_NAME}
          """
        }
      }
    }
  }
}
