metadata:
  label: 'skaffold'
spec:
  containers:
  - name: skaffold-container
    image: makotow/skaffold-docker:1.0-v0.34.0
    command:
    - cat
    tty: true
    alwaysPullImage: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: host-volume
  volumes:
    - name: host-volume
      hostPath:
        path: /var/run/docker.sock
