apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: skaffold-container
    image: registry.ndxlab.net/library/skaffold-docker:1.0-v0.34.0
    command:
    - cat
    tty: true
    alwaysPullImage: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: host-volume
  volumes:
    - name: host-volume
      hostPath:
        path: /var/run/docker.sock
